"""Data constants: document categories and country database (extracted from original HTML)."""

CATEGORIES = [
    {"key": "applicationLetter", "label": "Application Letter by the CEO of the Company", "group": "Cover Letters", "scope": "general"},
    {"key": "statementLetter", "label": "Statement Letter", "group": "Cover Letters", "scope": "general"},
    {"key": "pactOfIntegrity", "label": "Letter of Undertaking / Pact of Integrity", "group": "Cover Letters", "scope": "general"},
    {"key": "taxId", "label": "Tax Identification Number of the Company", "group": "Tax Documents", "scope": "country"},
    {"key": "annualTaxReturn", "label": "Reporting Evidence — Annual Income Tax Return (previous year)", "group": "Tax Documents", "scope": "country"},
    {"key": "otherTax", "label": "Other Tax Documents", "group": "Tax Documents", "scope": "country"},
    {"key": "boardOwnership", "label": "List of Board of Directors, Board of Commissioners & Ownershare", "group": "Legal & Ownership", "scope": "country"},
    {"key": "companyRegistration", "label": "Certificate of Company Registration", "group": "Legal & Ownership", "scope": "country"},
    {"key": "businessLicense", "label": "Company Business License(s)", "group": "Legal & Ownership", "scope": "country"},
    {"key": "domicile", "label": "Certificate of Domicile / Certificate of Residence", "group": "Legal & Ownership", "scope": "country"},
    {"key": "deed", "label": "Deed of Company Establishment & its Amendments", "group": "Legal & Ownership", "scope": "country"},
    {"key": "bankReference", "label": "Bank Reference Letter", "group": "Bank & Financial", "scope": "general"},
    {"key": "financialAudit", "label": "Financial Audit Reports", "group": "Bank & Financial", "scope": "general"},
    {"key": "workExperience", "label": "Company's Work Experience List (last 5 years)", "group": "Work Experience", "scope": "general"},
    {"key": "completionCertificate", "label": "Contract & Completion Certificate / Minutes of Acceptance", "group": "Work Experience", "scope": "general"},
    {"key": "safetyCert", "label": "Certificate of Contractor Safety Management System (Optional)", "group": "Optional Documents", "scope": "general"},
    {"key": "equipmentList", "label": "Company's Equipment List (Optional)", "group": "Optional Documents", "scope": "general"},
    {"key": "representativePermission", "label": "Representative Permission / Power of Attorney (Optional)", "group": "Optional Documents", "scope": "general"},
]

COUNTRY_DB = {
    "Singapura": {"tag": "SG", "apostille": True, "categories": {
        "boardOwnership": {"example": "ACRA Business Profile — Register of Company Officers & Shareholders", "concern": "Cocokkan nama & % kepemilikan shareholder dengan form aplikasi; cek nominee shareholder."},
        "companyRegistration": {"example": "ACRA Certificate of Incorporation / Business Profile (BizFile)", "concern": "Cek nomor UEN dan status \"Live\"."},
        "businessLicense": {"example": "Izin sektor spesifik dari otoritas terkait (mis. MAS untuk finansial), bila berlaku", "concern": "Cek apakah izin masih berlaku sesuai jenis usaha vendor."},
        "domicile": {"example": "Registered Office Address pada ACRA Business Profile", "concern": "Cocokkan dengan alamat surat aplikasi."},
        "deed": {"example": "Memorandum & Articles of Association (M&AA) / Constitution", "concern": "Cek amandemen terakhir bila ada perubahan struktur."},
        "taxId": {"example": "Tax Reference Number / UEN dari IRAS", "concern": "UEN sama dengan nomor di ACRA (satu nomor untuk keduanya)."},
        "annualTaxReturn": {"example": "Notice of Assessment (NOA) / Form C-S filing acknowledgement dari IRAS", "concern": "Cek tahun pajak sesuai & status \"Filed\"."},
        "otherTax": {"example": "GST Registration Certificate (jika terdaftar GST)", "concern": "Cek apakah vendor wajib GST berdasarkan omzet."},
    }},
    "Amerika Serikat": {"tag": "US", "apostille": True, "categories": {
        "boardOwnership": {"example": "Statement of Information / Beneficial Ownership Information (BOI) report — FinCEN", "concern": "Cocokkan nama officer/director & % ownership dengan BOI report terbaru."},
        "companyRegistration": {"example": "Certificate of Incorporation / Certificate of Good Standing — Secretary of State", "concern": "Cek status \"Active/Good Standing\" & tanggal terbit."},
        "businessLicense": {"example": "State/local Business License atau industry-specific license", "concern": "Cek license sesuai state operasional vendor."},
        "domicile": {"example": "Registered Agent Address / alamat pada Certificate of Good Standing", "concern": "Pastikan alamat registered agent bukan alamat fiktif."},
        "deed": {"example": "Articles of Incorporation / Certificate of Formation (LLC)", "concern": "Nama legal harus sama persis di semua dokumen."},
        "taxId": {"example": "EIN (Employer Identification Number) — IRS letter / form W-9 / SS-4", "concern": "EIN harus sama antara IRS letter dan W-9."},
        "annualTaxReturn": {"example": "Form 1120 / 1120-S filing acknowledgement atau IRS tax transcript", "concern": "Cek tahun pajak dan status filed."},
        "otherTax": {"example": "Form W-8BEN-E (withholding tax vendor asing)", "concern": "Cek FATCA status dan treaty claim."},
    }},
    "Inggris / UK": {"tag": "UK", "apostille": True, "categories": {
        "boardOwnership": {"example": "Companies House — Persons with Significant Control (PSC) register & Confirmation Statement", "concern": "Cocokkan pemegang saham >25% dengan data aplikasi."},
        "companyRegistration": {"example": "Certificate of Incorporation — Companies House", "concern": "Cek Company Number aktif (status \"Active\")."},
        "businessLicense": {"example": "Sector-specific license (mis. FCA untuk finansial)", "concern": "Cek berlaku sesuai bidang usaha."},
        "domicile": {"example": "Registered Office Address — Companies House", "concern": "Cocokkan dengan alamat pada surat aplikasi."},
        "deed": {"example": "Memorandum & Articles of Association", "concern": "Cek versi terbaru jika ada amandemen."},
        "taxId": {"example": "UTR (Unique Taxpayer Reference) / VAT Registration Certificate", "concern": "Cocokkan UTR dengan Companies House record."},
        "annualTaxReturn": {"example": "Corporation Tax Return (CT600) acknowledgement — HMRC", "concern": "Cek tahun pajak dan status submitted."},
        "otherTax": {"example": "VAT Return filing evidence", "concern": "Cek apakah vendor wajib VAT registered."},
    }},
    "Hong Kong": {"tag": "HK", "apostille": True, "categories": {
        "boardOwnership": {"example": "Annual Return (NAR1) — Directors & Shareholders, Companies Registry", "concern": "Cocokkan nama direktur & % saham dengan NAR1 terbaru; cek nominee shareholder."},
        "companyRegistration": {"example": "Certificate of Incorporation — Companies Registry (CR)", "concern": "Cek Company Registration Number & status aktif di CR search."},
        "businessLicense": {"example": "Business Registration Certificate (BR) — Inland Revenue Department", "concern": "Cek tanggal berlaku BR, wajib diperpanjang berkala."},
        "domicile": {"example": "Registered Office Address pada CR / NAR1", "concern": "Cocokkan dengan alamat surat aplikasi."},
        "deed": {"example": "Articles of Association", "concern": "Cek amandemen terbaru bila ada perubahan modal."},
        "taxId": {"example": "Business Registration (BR) Number", "concern": "BR Number harus sama antara BR Certificate dan NAR1."},
        "annualTaxReturn": {"example": "Profits Tax Return acknowledgement — IRD", "concern": "Cek tahun pajak sesuai & status submitted."},
        "otherTax": {"example": "Employer's Return (jika relevan)", "concern": "Cek kewajiban pajak tambahan sesuai jenis usaha."},
    }},
    "Jepang": {"tag": "JP", "apostille": True, "categories": {
        "boardOwnership": {"example": "Toukibo Touhon (Certificate of Registered Matters) — Representative Director/Officers", "concern": "Cocokkan nama representative director dengan penandatangan; minta terjemahan resmi."},
        "companyRegistration": {"example": "Certificate of Registered Matters — Legal Affairs Bureau", "concern": "Cek tanggal terbit maksimal 3 bulan terakhir."},
        "businessLicense": {"example": "Izin usaha sektor spesifik (mis. lisensi METI/FSA)", "concern": "Cek berlaku sesuai jenis usaha vendor."},
        "domicile": {"example": "Alamat Head Office pada Toukibo Touhon", "concern": "Cocokkan dengan alamat pada surat aplikasi."},
        "deed": {"example": "Articles of Incorporation (Teikan)", "concern": "Cek versi Teikan terbaru bila ada amandemen."},
        "taxId": {"example": "Corporate Number (Houjin Bangou) — National Tax Agency", "concern": "Cocokkan 13-digit Corporate Number di semua dokumen."},
        "annualTaxReturn": {"example": "Corporate Tax Return (Houjinzei Shinkokusho) acknowledgement", "concern": "Cek tahun fiskal & status diterima."},
        "otherTax": {"example": "Consumption Tax filing evidence (jika berlaku)", "concern": "Cek status registrasi consumption tax bila omzet melebihi threshold."},
    }},
    "Australia": {"tag": "AU", "apostille": True, "categories": {
        "boardOwnership": {"example": "ASIC Current & Historical Company Extract — Officeholders/Shareholders", "concern": "Cocokkan director & shareholder dengan ASIC extract terbaru."},
        "companyRegistration": {"example": "Certificate of Registration of a Company — ASIC", "concern": "Cek ACN aktif via ASIC Connect search."},
        "businessLicense": {"example": "State/Federal license sesuai bidang usaha", "concern": "Cek license berlaku di state operasional vendor."},
        "domicile": {"example": "Registered Office Address pada ASIC extract", "concern": "Cocokkan dengan alamat surat aplikasi."},
        "deed": {"example": "Certificate of Registration / Constitution", "concern": "Cek amandemen constitution bila relevan."},
        "taxId": {"example": "ABN (Australian Business Number) & ACN", "concern": "Verifikasi ABN aktif via ABN Lookup, cocokkan nama legal entity."},
        "annualTaxReturn": {"example": "Notice of Assessment — ATO", "concern": "Cek tahun pajak & status assessed."},
        "otherTax": {"example": "GST Registration confirmation (jika terdaftar)", "concern": "Cek kewajiban GST berdasarkan omzet."},
    }},
    "Jerman": {"tag": "DE", "apostille": True, "categories": {
        "boardOwnership": {"example": "Handelsregisterauszug — Geschäftsführer (Directors) & Gesellschafterliste (Shareholders)", "concern": "Cocokkan nama Geschäftsführer & shareholder list dengan aplikasi."},
        "companyRegistration": {"example": "Handelsregisterauszug (Commercial Register Extract) — Amtsgericht", "concern": "Cek HRB Number dan tanggal extract terbaru."},
        "businessLicense": {"example": "Gewerbeanmeldung (Trade License), bila relevan", "concern": "Cek izin berlaku sesuai jenis usaha."},
        "domicile": {"example": "Sitz der Gesellschaft (Registered Seat) pada Handelsregister", "concern": "Cocokkan alamat dengan surat aplikasi."},
        "deed": {"example": "Gesellschaftsvertrag / Satzung (Articles of Association)", "concern": "Cek amandemen terbaru jika ada perubahan modal/struktur."},
        "taxId": {"example": "Steuernummer & USt-IdNr. (VAT ID) — Finanzamt", "concern": "Cocokkan Steuernummer di semua dokumen resmi."},
        "annualTaxReturn": {"example": "Körperschaftsteuererklärung (Corporate Tax Return) acknowledgement", "concern": "Cek tahun pajak & status eingereicht (submitted)."},
        "otherTax": {"example": "Umsatzsteuervoranmeldung (VAT filing) evidence", "concern": "Cek kepatuhan pelaporan VAT berkala."},
    }},
    "India": {"tag": "IN", "apostille": False, "categories": {
        "boardOwnership": {"example": "MCA Master Data — Director/DIN & Shareholding pattern (Form MGT-7)", "concern": "Cocokkan DIN direktur & shareholding dengan MCA portal."},
        "companyRegistration": {"example": "Certificate of Incorporation — MCA (CIN Number)", "concern": "Cek CIN aktif & status \"Active\" di MCA portal."},
        "businessLicense": {"example": "Shop & Establishment License / sector license", "concern": "Cek license berlaku sesuai lokasi & jenis usaha."},
        "domicile": {"example": "Registered Office Address pada Certificate of Incorporation", "concern": "Cocokkan alamat dengan surat aplikasi & bukti sewa/kepemilikan."},
        "deed": {"example": "Memorandum of Association (MOA) & Articles of Association (AOA)", "concern": "Cek amandemen MOA/AOA terbaru."},
        "taxId": {"example": "PAN (Permanent Account Number) & GSTIN", "concern": "Cocokkan PAN antara Certificate of Incorporation dan dokumen pajak lain."},
        "annualTaxReturn": {"example": "Income Tax Return (ITR) acknowledgement tahun sebelumnya", "concern": "Cek assessment year sesuai & status filed."},
        "otherTax": {"example": "GST Return filing evidence (GSTR)", "concern": "Cek kepatuhan pelaporan GST bulanan/tahunan."},
    }},
    "Malaysia": {"tag": "MY", "apostille": True, "categories": {
        "boardOwnership": {"example": "e-Info SSM — Particulars of Directors & Shareholders", "concern": "Cocokkan nama direktur & shareholder dengan e-Info SSM terbaru."},
        "companyRegistration": {"example": "Certificate of Incorporation — SSM (Suruhanjaya Syarikat Malaysia)", "concern": "Cek nomor registrasi & status aktif di SSM."},
        "businessLicense": {"example": "Business/sector license sesuai bidang usaha", "concern": "Cek license berlaku & sesuai aktivitas usaha."},
        "domicile": {"example": "Registered Office Address pada e-Info SSM", "concern": "Cocokkan dengan alamat surat aplikasi."},
        "deed": {"example": "Constitution / Memorandum & Articles of Association", "concern": "Cek amandemen terbaru bila relevan."},
        "taxId": {"example": "Tax Identification Number (TIN) — LHDN", "concern": "Cocokkan TIN dengan dokumen registrasi perusahaan."},
        "annualTaxReturn": {"example": "Income Tax Return (Form C) acknowledgement — LHDN", "concern": "Cek tahun taksiran & status filed."},
        "otherTax": {"example": "SST Registration evidence (jika berlaku)", "concern": "Cek kewajiban Sales & Service Tax berdasarkan omzet."},
    }},
    "Tiongkok": {"tag": "CN", "apostille": True, "categories": {
        "boardOwnership": {"example": "National Enterprise Credit Info / Business License — Legal Representative & Shareholders", "concern": "Cocokkan Legal Representative & shareholder dengan National Enterprise Credit Information System."},
        "companyRegistration": {"example": "Business License (营业执照) dengan Unified Social Credit Code", "concern": "Cek masa berlaku & status aktif lisensi."},
        "businessLicense": {"example": "Izin usaha tambahan sesuai sektor (jika relevan)", "concern": "Cek kesesuaian scope of business pada Business License."},
        "domicile": {"example": "Registered Address pada Business License", "concern": "Cocokkan alamat dengan surat aplikasi."},
        "deed": {"example": "Articles of Association (公司章程)", "concern": "Cek amandemen terbaru bila ada perubahan struktur."},
        "taxId": {"example": "Unified Social Credit Code", "concern": "Cocokkan Unified Social Credit Code di semua dokumen."},
        "annualTaxReturn": {"example": "Corporate Income Tax Return filing evidence", "concern": "Cek tahun pajak & status filed ke otoritas pajak lokal."},
        "otherTax": {"example": "VAT Invoice (Fapiao) registration evidence", "concern": "Cek status registrasi fapiao/VAT sesuai skala usaha."},
    }},
}

WORKFLOW_STATUSES = ["DRAFT", "IN_REVIEW", "CLARIFICATION", "PENDING_APPROVAL", "RETURNED", "APPROVED", "MYSSC_REQUESTED", "COMPLETED"]
